### ISSUE TITLE
support of GetPublicData API

### ISSUE THREAD

**Issue by SebastienPittet** [philippelt/netatmo-api-python#10]
Hello !

I noticed the awesome code you wrote for interacting with netatmo data. **Many thanks for that !**
However, I need to access the public data through "[GetPublicData API](https://dev.netatmo.com/dev/resources/technical/reference/weatherapi/getpublicdata)" and the code does not (yet) support it.

Do you think someone can provide this ?

As an absolute beginner in development, I'm almost sure you couldn't accept a pull request with my poor code quality. But if someone can [check my repo ](https://github.com/SebastienPittet/netatmo-api-python/blob/master/lnetatmo.py)and give some advices, this will be greatly appreciated.

Maybe my work can inspire someone?

**Comment by philippelt** [comment]
Hello Sebastien,

you have already done a very good job. May I suggest : 
 - in the __init__ function of PublicData class : 
    - default "required_data" to None  to allow for people who wants all stations even if they don't supply rain or humidity
    - default filter to "true" as most of the time, station with ill relevant values are of no interest (like external sensor setup in a wrong place and displaying abnormal values). You are right because it's the opposite default value of Netatmo but I prefer the policy that allow for unexperienced developers to increase chance to get good results

The get information should use a measurement name to allow for something else that rain_24h.

The difficulty with getpublicdata is that there are many usage patterns depending of the goal of each one. It's hard to implement all kind of requests that can be done to satisfy all patterns.

If that is Ok for you, I can just add the PublicData class in my code and potential users will have to deal with the rawData response which should not be complex as it is just browsing Python dictionaries.

**Comment by SebastienPittet** [comment]
...Thanks for your comments. Working on it... ;-)

**Comment by sunithak** [comment]
Hello, I am trying to access the public data by using your code. Thank you very much. When i am trying to update required_type to None. It is giving me error. I need huge amount of data to calculate the predictions. Thank you.

**Comment by SebastienPittet** [comment]
Hello,
Please provide me the error you get, with all details. I will use that to improve the code.
You can submit your issues on my repo (I enabled the feature). Once corrected, I will PR to this repo.
Kind regards.

[Link to submit issues](https://github.com/SebastienPittet/netatmo-api-python/issues)

**Comment by sunithak** [comment]
Traceback (most recent call last):
  File "C:\Users\Sunitha\workspace\sunitha\netatmo-api-python-master\GetPublicData.py", line 652, in <module>
    LON_SW = 6.62417)
  File "C:\Users\Sunitha\workspace\sunitha\netatmo-api-python-master\GetPublicData.py", line 150, in __init__
    resp = postRequest(_GETPUBLIC_DATA, postParams)
  File "C:\Users\Sunitha\workspace\sunitha\netatmo-api-python-master\GetPublicData.py", line 575, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Sunitha\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by SebastienPittet** [comment]
Bad request means I need to see how do you create your object.
Do you have Something like this:
`
Area = PublicData(authorization, 
                LAT_NE = 46.80761,
                LON_NE = 6.64530,
                LAT_SW = 46.76671,
                LON_SW = 6.62417,
                required_data_type = 'rain',
                filtering = True)
`
What data are you looking for ? rain ? humidity ? both ?

**Comment by sunithak** [comment]
Thank you for the reply. I would like to read all the public data with rain and humidity both. And i want to read data from one country for one month duration. I would like to predict the temperature and data in the area where there are no stations. So i would like to read all the data regardless rain or humidity.

**Comment by sunithak** [comment]
Hello Sebastien,
Thank you very much for the code. Yes. I am also using the same code. I would like to retrieve whole data area wise like temperature, humidity, wind, pressure etc. I am new to coding also. I would like predict these where there is no station. For that, i would like retrieve all whether data with station into mysql. Could you suggest an easy way. And for some areas lon and lat, the code is working, for some it is not. Is there anyway to calculate lan_ne, lon_ne, lat_sw and lon_sw from GPS coordinates. Thank you.

**Comment by sunithak** [comment]
Hello,
The code is running perfectly. How can i retrieve huge data at once. If i am giving coordinates for larger areas it is giving error. And i would like to retrieve all the netatmo readings like all the whether data na_Temperature, na_MaxTemp, na_MinTemp,  na_TempTrend, na_TemperatureOutdoor, na_TemperatureOutdoorMax, na_TemperatureOutdoorMin, na_TemperatureOutdoorTrend, na_HumidityOutdoor, na_Humidity, na_Pressure, na_Rain, na_Rain_sum1, na_Rain_sum24, na_battery_base_percent, na_battery_rain_percent, na_battery_outdoor_percent, modulecount. 
By using using your code, i am getting stations. Could you help me? Thank you.
