### ISSUE TITLE
JSONDecodeError: Unterminated String

### ISSUE THREAD

**Issue by NicolasRigo** [philippelt/netatmo-api-python#11]
Hello,

I just found this very interesting python library for getting access to my Netatmo devices.
Thank you for this!

Unfortunately, when trying to get access to my home devices, postRequest method returns an exception when trying to return the response in JSON format.

It happens when testing the library from class HomeData tryng to request _GETHOMEDATA_REQ api.

json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 65528 (char 65527)

The returned string is effectively not well formed.

Any idea?

Many thanks in advance for your help!

Nicolas

**Comment by philippelt** [comment]
The allowed buffer size is now insufficient with large home data request response. The response size is now unlimited (but read in 64K chunks).
Fixed in b7453a19872bc686b9026a236e67bf0d08ad272c
