### ISSUE TITLE
Http Error 400 Bad Request

### ISSUE THREAD

**Issue by marco123445** [philippelt/netatmo-api-python#12]
Hello
The program does not work anymore. I get from the urllib the error message 400, but I have not changed anything. The log file from the app also says nothing. Any ideas?

thanks for your help
 ```
Entering post mortem debugging...
****************************************
   648 class HTTPDefaultErrorHandler(BaseHandler):
1   649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650      raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):
```

**Comment by philippelt** [comment]
What is the version you are using ?
Any stack trace and error msg ? (the HTTPError class parameters)
Without any more information, I will not be able to help you...

**Comment by pgirolami** [comment]
Same here on a raspbery pi using the version available to install via "pip3"

`pi@raspberrypi ~/netatmo $ python3 run.py
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    authorization = lnetatmo.ClientAuth()
  File "/usr/local/lib/python3.4/dist-packages/lnetatmo.py", line 118, in __init__
    resp = postRequest(_AUTH_REQ, postParams)
  File "/usr/local/lib/python3.4/dist-packages/lnetatmo.py", line 541, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request`

**Comment by philippelt** [comment]
Could you double check you authentication data ?

 - ``.netatmo.credentials`` must be located in the home directory (and have appropriate permissions) of the username of the running program (if you use cron, it may be root for example and not you home user)

 - Ensure that the credentials contains all 4 keys is you are not supplying more data elsewhere (``CLIENT_ID, CLIENT_SECRET, USERNAME, PASSWORD``) and that the format is OK.

You can test that your authentication is OK by running the library as a standalone program : $ python3 lnetatmo.py

**Comment by pgirolami** [comment]
I'm running it by hand, file looks good to me
```pi@raspberrypi ~/netatmo $ ls -lah ~/.netatmo.credentials
-rw-r--r-- 1 pi pi 180 Jun 18 12:27 /home/pi/.netatmo.credentials```

Regarding the credentials, the only one that could be wrong is the username, is that the email for the account ?

**Comment by philippelt** [comment]
Yes the username is the email address you used as Netatmo account.

In doubt, you could add a print command just before the line 605 ``if not _CLIENT_ID or not _CLIEN...``to print all 4 items actually used when auto-test.

By default, the file is read as UTF-8 encoded.

I assume that you are confident about the client_id and client_secret that you are using (and that they are allowed on the requested account) ?

**Comment by marco123445** [comment]
When i print my data right before 602....
`>>> runfile('C:/Users/marco/Anaconda3/Lib/lnetatmo.py', wdir='C:/Users/marco/Anaconda3/Lib')
data %d 59425095c8bd0073618b559c JTqrtlmxxLDwb9koFraj0wCYAuNYS marco mypassword
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    response = meth(req, response)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
>>>   File "C:\Users\marco\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\Users\marco\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/marco/Anaconda3/Lib/lnetatmo.py", line 602, in <module>
    authorization = ClientAuth()  # Test authentication method
  File "C:/Users/marco/Anaconda3/Lib/lnetatmo.py", line 111, in __init__
    resp = postRequest(_AUTH_REQ, postParams)
  File "C:/Users/marco/Anaconda3/Lib/lnetatmo.py", line 543, in postRequest
    resp = urllib.request.urlopen(req, params)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\marco\Anaconda3\lib\urllib\request.py", line 532, in open
`

Should my username still be my email? When i run the code on my raspi the username is root so....

**Comment by philippelt** [comment]
The username property for the authentication should be your email address. It's the same that the netatmo web account so it's easy to test. In the data above, I think that you are using "marco" which is probably not the expected username.

I just realized that I did not mention that field names in the ``.netatmo.credentials`` must be mandatory in UPPERCASE characters or it may fail with an authentication bad request ! I will fix this in the next release to handle the case where keys would be lowercase.

According to the Netatmo documentation, a "Bad request", and I suppose it's what they mention as an "Invalid request" is only returned when "The request is missing a required parameter, includes an unsupported parameter or parameter value, or is otherwise malformed." So an invalid username should get a response of access denied or equivalent, thus the real problem should be somewhere else.

Just be sure to use the last version from github, just in case.

As the parameter list in the library is the right one, I think that there can only be a bad value somewhere in the 4 parameters.

As a side remark, I noticed that your client_id is 24 chars, like mine, but the secret (if you did not truncate it) is 29 chars, mine is 40. Are you sure of your client_secret ?

I suggest, if not already done, that you revoke them and recreate them as they have been posted and could eventually be used by other readers. Of course, if you posted fake data, there is no issue then.

**Comment by marco123445** [comment]
I do not use the `.netatmo.CREDENTIALS` file. I define my AUTH data directly in the library. So the error must be somewhere else.
I have reseted my Netatmo app and got a larger client id, so it should be all right

**Comment by marco123445** [comment]
`print("user", getParameter("USERNAME", cred))`

Even if I read the `USERNAME` directly, root comes back

**Comment by marco123445** [comment]
I have solved the problem by linking the `_USERNAME` directly with my email

# 3 : Override final value with content of env variables if defined
_CLIENT_ID     = getParameter("CLIENT_ID", cred)
_CLIENT_SECRET = getParameter("CLIENT_SECRET", cred)
_USERNAME      = "my@email.ch"#getParameter("USERNAME", cred)
_PASSWORD      = getParameter("PASSWORD", cred)
print("user", getParameter("USERNAME", cred))

And now it works fine again...

**Comment by philippelt** [comment]
OK, I understand you already have an exported environment variable USERNAME set with your OS login name and it is overwriting your Netatmo username.

From what I can see on a pi from Raspbian Jessie, logged as root, I don't have that. Nore I have it on a bigger server on Ubuntu LTS 14.04. On my machines, the environment variable for the login name is ``LOGNAME`` on both environment.

The easiest solution to solve your problem, without modifying any code, you must unset any environment variable that may interfere (eg ``$ unset USERNAME`` here) before running your code .

Thanks for taking the time to provide this valuable feedback ! Your are probably helping others.
Yours

**Comment by pgirolami** [comment]
At this point I'm stumped
- I've gotten the code to print out the parameters it's putting in the request: they're what I expect
- I've re-generated my key and token (incidently, the toke went from 31 characters to 44)
- I've checked the email and password by logging-in using them
- I've cloned the repo and run the lnetatmo.py script found in the repo

I'm still getting that 400 error !

**Comment by pgirolami** [comment]
Ah... just got it to work. After doing all of the above, I made sure to "Activate" the app and it now works.

So my guess is : the token you get when you create the app is bad. You need to regenerate it. When you regenerate it, you need to re-activate too.

**Comment by philippelt** [comment]
Thanks for the feedback !

**Comment by cwaidner** [comment]
I have the same problem, regenarating my API keys does not work.
I'm running Python on Windows, py lnetatmo.pl results in the same 400 as shown above.

`py -3 lnetatmo.py
Traceback (most recent call last):
  File "lnetatmo.py", line 612, in <module>
    authorization = ClientAuth()  # Test authentication method
  File "lnetatmo.py", line 119, in __init__
    resp = postRequest(_AUTH_REQ, postParams)
  File "lnetatmo.py", line 553, in postRequest
    resp = urllib.request.urlopen(req, params)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request`

I'm using a .netatmo.credentials in my home directory (C:\Users\Chris\.netatmo.credentials), all keys are uppercase. User + Password are definitely correct. Any ideas how to fix this?

**Comment by cwaidner** [comment]
Ok, debugged your code. Problem is the username, it is always pulled from the environment variable (why?). On Windows "Username" is my Windows logon name, which of course does not match with my netatmo account.
Any way to fix this easily without overwriting my Windows session variables?

**Comment by philippelt** [comment]
I am reluctant to change environment variables names as it matches Netatmo API names & credentials file keys and users may already using them. This would be a compatibility breaking change.

Sorry, but since I no longer use windows for a very long time, I didn't anticipate that USERNAME environment variable could be a problem. On Linux or OSX, the equivalent is just USER so there is no interference.

If you can't "unset" (I don't know the windows equivalent) the env variable before launch of your program, you can always call lnetatmo.ClientAuth with all parameters (clientId, clientSecret, username, password) that you would have get using any method (including reading yourself .netatmo.credentials).

With such method, no override of any kind would occur.

**Comment by cwaidner** [comment]
Thank you for the fast reply - but at least the problem is clear for me and I can work around it in some way.
