### ISSUE TITLE
ValueError: Empty certificate data

### ISSUE THREAD

**Issue by Psychokiller1888** [philippelt/netatmo-api-python#13]
Hi!

First of all, thank you so much for this, I have tried it directly on my Raspberry Pi3 it worked like a charm.

I'm a bit lazy and don't really enjoy Raspbian and dev'ing directly on it, so for some reason I have put in my head to make it work with..... Visual Studio 2017

Got everything working, even managed to make it load lnetatmo!

Unfortunately, when trying to

netatmoAuth = lnetatmo.ClientAuth(clientId, clientSecret, username, password)

And deploying to my Raspberry, the execution stops and VS returns me an error saying:

"ValueError: Empty certificate data" or sometimes
"urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>"

I'm not saying this is lnetatmo's problem, but maybe you have a slight idea of what could cause this?

Cheers!

**Comment by philippelt** [comment]
Hello,

nice move, you could publish some of your work as others could be interested.

You are encountering a SSL certificate validation error. It means that your code doesn't have access to the certificate stores where all certification authorities certificates are located. To confirm the validity of the Netatmo server certificate, your code require the "Go Daddy Secure Certificate Authority - G2" authority certificate.

I don't use Visual studio and there are many different ways to register a set of certificate authorities for server certificate validation, it highly depends of your platform.

An alternative solution is to modify the lnetatmo.py library to explicitely supply the above certificate for validation.

Yours

**Comment by Psychokiller1888** [comment]
OMG, why didn't I think about it? The famous "ca-bundle.crt" I totally know about because I spent hours in the past fixing the same on some  PHP implementation? This is why internet is great, thank you for guiding me. And sorry for polluting your issue reporter with this ;)

**Comment by philippelt** [comment]
No problem, you are welcome
;-)
