### ISSUE TITLE
Fails to retrieve weather data if outdoor module doesn't have a name set

### ISSUE THREAD

**Issue by pgirolami** [philippelt/netatmo-api-python#14]
#When I installed my weather station, I didn't end up having a module_name for my outdoor module. It shows up as "noname" on the web config popup and the API returns no module_name field. Hence the error
```  
File "./run.py", line 27, in <module>
    ( devList.lastData()['internal']['Temperature'],
  File "/usr/local/lib/python3.4/dist-packages/lnetatmo.py", line 231, in lastData
    lastD[module['module_name']] = ds.copy()
KeyError: 'module_name'`

**Comment by philippelt** [comment]
Thanks for reporting.
Fixed in 524f2a5fa3d5cc448e5e67d59a6c5092692669ed
