### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by DanielIbaseta** [philippelt/netatmo-api-python#15]
I am trying to pull data from Netatmo using your library and I was able to do it until now. For some reason my application stopped working with a 403 HTTP error when trying to do this:

```weatherData = lnetatmo.WeatherStationData(authorization)```

This is the error:
```
Traceback (most recent call last):
  File "netatmo_test.py", line 9, in <module>
    weatherData = lnetatmo.WeatherStationData(authorization)
  File "/usr/local/lib/python2.7/dist-packages/lnetatmo.py", line 171, in __init__
    resp = postRequest(_GETSTATIONDATA_REQ, postParams)
  File "/usr/local/lib/python2.7/dist-packages/lnetatmo.py", line 546, in postRequest
    resp = urllib2.urlopen(req).read(body_size)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

The authorization variable is well set and everything is configured, like I said, it worked for 2 hours straight. I thought it could the expiration date but it is not as it is set to 15:50 (13:07 now). After a 10 or so minutes it came back to normal and now I am able to pull data again. Have you experienced any of this? I would like to know the cause. Thank you for the library, it is a great work.

**Comment by philippelt** [comment]
Hello,

you should review you API calls rate to ensure it is compliant with Netatmo API rate policy (https://dev.netatmo.com/resources/technical/guides/ratelimits)

If you exceed the authorized threshold, any new authentication would be rejected and, if you have an existing token (which is your case), it is expired even before it's expected end of life thus you will get a 403 forbidden error which correspond to an invalid token.

You just have to wait to regain API call "credits".

If you are interested with live datas, you should not have any problem as it is useless to ask for data more than every 10min which is near to the data refreshing rate.

If your are requesting past data for statistics purpose, then you should ensure that your rate request is compliant with the policy and avoid expecting 403 errors to slow down, your account could eventually be considered offending in such case.

**Comment by DanielIbaseta** [comment]
Thanks, I didn't know about those limits. Decreasing my request rate solved it.
