### ISSUE TITLE
compatibility with netatmo homecoach device

### ISSUE THREAD

**Issue by cderv** [philippelt/netatmo-api-python#16]
Hi, 

thank you for your help with Netatmo API ! 

Do you have plan on support homecoach device ? 
This is the endpoint https://api.netatmo.com/api/gethomecoachsdata
I notice it is not available yet.

thank you.

**Comment by philippelt** [comment]
Hello,

thanks for you message.

I hate pushing untested code and I don't own and do not have access to an homecoach device. If you can provide my (using direct mail) temporary access to a homecoach device, I could easily add support as it looks barely like a lightweight weather station...

**Comment by cderv** [comment]
Oh sorry. I had other project that get in the way. Was not anymore on top of my list. I have a home coach. I need to find how to get you access.
