### ISSUE TITLE
Run on Raspberry Pi3

### ISSUE THREAD

**Issue by Magic-Pi** [philippelt/netatmo-api-python#17]
Hi,

Thank you for the python script to read the data from netatmo. After the installation of lnetatmo.py I want to import the script in a new python code but I get the following message:
lnetatmo.py : warning, no home available for testing
lnetatmo.py : OK

Do you know this problem? I updated the client_id,secret and my username and password, respective. 

Thanks in advance

**Comment by philippelt** [comment]
As you already closed the issue, I assume you understood that it was just a warning saying that your account do not have a home defined and associated security devices and the corresponding code can’t be tested.
If you want to use only a weather station, you can safely ignore this warning.
Enjoy
