### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by KrunchMuffin** [philippelt/netatmo-api-python#18]
Hi,

When running the simple sample I get the following error...

> Traceback (most recent call last):
  File "samples/simpleLastData", line 12, in <module>
    authorization = lnetatmo.ClientAuth()
  File "/usr/local/lib/python3.5/dist-packages/lnetatmo.py", line 153, in __init__
    self._accessToken = resp['access_token']
TypeError: 'NoneType' object is not subscriptable

I have set up the app and inserted credentials. Not sure what the issue is?

**Comment by philippelt** [comment]
You probably have invalid data in the given credentials. Which method are you using (hard coded in library source or credential file ?) Could you double check these data.

If you are running on windows, take care to the fact that the USER environment variable is already used by the OS. You should "unset" it before running.

**Comment by KrunchMuffin** [comment]
I tried in the file and in hard coded.

I ended up installing HASS tho.
