### ISSUE TITLE
Add Netatmo radiator

### ISSUE THREAD

**Issue by lwt2** [philippelt/netatmo-api-python#22]
Hi

I wanted to add my Netatmo radiator in the Home Assistant, and that didn't work. After the search it turned out that the radiator cannot currently be included in the Home Assistant. I found your contribution in GitHub and I noticed that it still contains outdated code components. Unfortunately my programming skills are not so good otherwise I would help you rewrite that.

https://dev.netatmo.com/resources/technical/reference/deprecated

And the values I got back from the Dev Netatmo website might help you. If there's anything else I can do to help you, just say it.

>
body:

	homes:
		id: "5a99870413475d3a118c5386"
		name: "Home"
		altitude: 000
		coordinates:[...]
		country: "DE"
		timezone: "Europe/Bananaland"
		rooms:
			id: "1703702957"
			name: "Bedroom"
			type: "bedroom"
			module_ids:
				"09:00:00:00:93:02"
			measure_offset_NAPlug_temperature: 0
			measure_offset_NAPlug_estimated_temperature: 0
			id: "2331965531"
			name: "Living room"
			type: "livingroom"
			module_ids:
				"09:00:00:00:8d:cc"
			measure_offset_NAPlug_temperature: 0
			measure_offset_NAPlug_estimated_temperature: 0
		modules:
			[Object]
				id: "70:ee:50:0e:85:d4"
				type: "NAPlug"
				name: "Relay"
				setup_date: 1520011012
				modules_bridged:
					"09:00:00:00:8d:cc"
					"09:00:00:00:93:02"
			[Object]
				id: "09:00:00:00:8d:cc"
				type: "NRV"
				name: "Heater Living room"
				setup_date: 1520011025
				room_id: "2331965531"
				bridge: "70:ee:50:0e:85:d4"
			[Object]
				id: "09:00:00:00:93:02"
				type: "NRV"
				name: "HeaterBedroom"
				setup_date: 1520011025
				room_id: "1703702957"
				bridge: "70:ee:50:0e:85:d4"
		schedules:[...]
		therm_schedules:[...]
		therm_setpoint_default_duration: 60
		therm_mode: "schedule"

**Comment by philippelt** [comment]
Without access to a device for testing, I can't develop such code and the issue do not seems to have gain attention to potential contributors.

Closed as unable to add feature.
