### ISSUE TITLE
no modules

### ISSUE THREAD

**Issue by Nils154** [philippelt/netatmo-api-python#23]
My external module died, so now I have a home station without any modules.
several sections of the code expect there to be at least one module and the code fails if there aren't any.
I was able to get it to work by putting Try/except/pass around the module loops in both __init__ and lastData.

pretty new to Github, so not sure how to upload the code changes, but thought I should mention it.

Thanks for the great code!

-Nils

**Comment by philippelt** [comment]
Thanks for notifying the problem.

I never anticipated a weather station without an external sensor but you are absolutely right, it is still usable for indoor measurement and I should handle this use case.

I will make the change as soon as possible but I am currently engaged in a lot of "business" work that I must deliver and can't found some spare time to return to my "shared" activities. Hope this will change in the second half of june

Again, thanks for notifying I would have had hard time to reproduce the situation to test the code :-)
