### ISSUE TITLE
ds['time_utc']can be null

### ISSUE THREAD

**Issue by Psychokiller1888** [philippelt/netatmo-api-python#24]
```
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/ProjectAlice/modules/RedQueen.py", line 45, in airQualityCheck
    data = netatmoModule.getDataFromNetatmo()
  File "/home/pi/ProjectAlice/modules/Netatmo.py", line 201, in getDataFromNetatmo
    return weatherData.lastData()
  File "/home/pi/ProjectAlice/libraries/lnetatmo.py", line 324, in lastData
    if ds['time_utc'] > limit:
KeyError: 'time_utc'
```

I just plugged a new wind and a new rain module

**Comment by Psychokiller1888** [comment]
Can be fixed by adding a check on lnetatmo.py, line 317, right after ds declaration

```		if 'time_utc' not in ds:
			return lastD```

Sorry, too lazy for a pull request and this is open to what it should return if it's not existing

**Comment by kugel2** [comment]
I had the same problem with 'time_utc' missing in the dashboard_data of my wind sensor. 
But if you do a ```return None``` then no data at all is returned, wouldn't it be better to just exclude the 'failing' module with a ```continue``` instead?
```
if 'time_utc' not in ds:
    continue
```

**Comment by philippelt** [comment]
Hello folks,

vacation time, back on track :-)

as time_utc is used to define "When" property and "When" is supposed to exist, to avoid breaking existing code I choose to define when with the curent timestamp.

Let me know if it works for you.
