### ISSUE TITLE
Value of device_id and module_id in graphLast3Days

### ISSUE THREAD

**Issue by andersenthomas** [philippelt/netatmo-api-python#3]
Hi,

I'm getting an urllib2.HTTPError 404: Not found when running this script. Any ideas?

I'm using 'name' module_id (in my case indoor) and device_id as station name (in my case aertebjerggaardvej)

**Comment by philippelt** [comment]
Hello,

I may help you but I need the full traceback information to understand the origin of the problem.

The error you mention doesn't look like a parameter issue (station or module names).
Did you customized the library with authentication data (CLIENT ID/PW, USER ID/PW) ?

**Comment by andersenthomas** [comment]
Hi,

The simpleLastData.py script executes fine and returns the expected data so I guess authentication data is not the issue? I am using Python 2.7 on Win7 if that makes any difference.

Traceback is attached below:
Traceback (most recent call last):
  File "graphLast3Days.py", line 31, in <module>
    date_end=now)
  File "C:\Users\thomas\Downloads\netatmo-api-python-master\netatmo-api-python-m
aster\lnetatmo.py", line 195, in getMeasure
    return postRequest(_GETMEASURE_REQ, postParams)
  File "C:\Users\thomas\Downloads\netatmo-api-python-master\netatmo-api-python-m
aster\lnetatmo.py", line 247, in postRequest
    resp = urllib2.urlopen(req).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by philippelt** [comment]
You are right, as an other example is running, I didn't had the info, it can't be an authentication problem.

I checked that, effectively, an incorrect id for the station or the device return (from netatmo) a 404 error which is not very explicit.

I didn't noticed initially that you are using names instead of id (which is a property of each object).

The Netatmo API require ID for getMeasure, not the name.

You can find the ID using the devList.stationByName("The station name")["_id"]
and the module ID using devList.moduleByName("The module name")["_id"]

devList being the returned instance of lnetatmo.DeviceList(auth)

These ID are of type string with the format "xx:yy:zz:aa:bb:cc"

Yours

**Comment by andersenthomas** [comment]
Thanks. That seems to work. I now got the code to run and display data. The devList.moduleByName("The module name")["_id"] only returns values from the outdoor module only returns the id. For the indoor module a "TypeError: 'NoneType' object has no attribute '__getitem__' " error is thrown. Is this by design that temperatures can only be fetched from the outdoor module or am I missing something obvious?

**Comment by andersenthomas** [comment]
Thanks! That seems to do the trick!

**Comment by philippelt** [comment]
moduleByName or stationByName returned None if the supplied name is not found.
If you are unsure of the names used, check them before requesting the value of the _id entry or you will have a "TypeError: 'NoneType' object has no attribute '__getitem_' " error...

**Comment by sunithak** [comment]
Hello,
I would like to retrieve the same data by using getpublicdata api. I dont have device id and module id. I would like to retrieve the raw data from one area for one month. I am trying your sample code. It is giving me http error. Please suggest me what to do.

**Comment by SebastienPittet** [comment]
You will have the device ID and module ID as a result to GetPublicData . The web service returns a list of devices and their associated modules.

**Comment by sunithak** [comment]
I would like to retrieve the whole output data like temperature, rain, Humidity, wind.. like all the data in whether map into csv by using getPublicData.
