### ISSUE TITLE
try/except URLError in postRequest() may be over-general

### ISSUE THREAD

**Issue by jackjansen** [philippelt/netatmo-api-python#31]
_postRequest_ is the workhorse in lnetatmo, and it uses a try/except `urllib.error.URLError` around the `urlopen()` call and returns `None` in case of errors. This will cause the caller to raise what it feels is the correct lnetatmo error, for example `AuthFailure`.

Unfortunately this masks networking errors. The case I ran in to was that my certificates were mis-configured (a common occurrence on OSX with Python `urllib.request`, unfortunately) and this showed up as `AuthFailure: Authentication request rejected`. This is rather difficult to debug.

I think catching only `urllib.error.HTTPError` in _postRequest_ may be better: the netatmo-reported errors would still cause the `None` return and raise the correct lnetatmo error, but underlying network errors (such as certificate errors, but also network connectivity problems and other issues that have nothing to do with netatmo) would let the `URLError` pass through.

**Comment by philippelt** [comment]
You are right.

My initial thoughts were that most errors would be programming errors from programs using library but time has demonstrated that users are facing, authentication, throttling, connectivity issues, server availabilities, and now certificate validation issues :-)...

This makes sense to contribute in solving problems connecting to Netatmo servers.

Good suggestion to use HTTPError in place of URLError as it gives direct access to the HTTP failure code that are "documented" in Netatmo return values.

It was a good opportunity to switch to the logging module so each may decide the way to handle log info.

Thanks for your contribution
