### ISSUE TITLE
Option to return data in imperial or metric

### ISSUE THREAD

**Issue by mcinflyre** [philippelt/netatmo-api-python#32]
Hi,

Thank you for your work on this project, it has benefited me greatly!  Netatmo has to option to return the data in imperial or metric values.  (unit : 0 -> metric system, 1 -> imperial system)

 Is it possible to modify the lnetatmo.py code to have the option?  Or, if it's not something that you think other people would want, can you point me in the right direction in your code where to change it?

Again, thank you for your work, it's greatly appreciated.

Richard

**Comment by philippelt** [comment]
Hello,

thanks for the remark. I made a change to add userinfo in the weatherdata instance. You can check it in the printAllLastData example.

This will allow to get units chosen by the user in the account setup. Unfortunately, I didn't found a temperatureunit like there is a pressureunit or windunit. I suppose that the global "unit" value of metric or imperial is a substitute for celsius or farenheit...

Added in 8b418ea3902d389862b7121caf981289f4054268

**Comment by mcinflyre** [comment]
Thank you for your information and help with this. 

Have a great weekend 

Thanks,

Richard

-----Original Message-----

**Comment by mcinflyre** [comment]
Hi Philippe,

I'm sorry to bother you again, I wanted to check with you on the units
returned from Netatmo.  I downloaded the your updated files and ran them
with my Netatmo credentials.  The Data units show 'imperial', however, the
data returned is still metric.  I included the output below so you can see
what was returned.  Do I need to change anything else, or should the script
return the data based only on how I have my Netatmo account setup?

Again, I can't thank you enough for this code, awesome job!

Thanks,

Richard

-- Output from printAllLastData with updated lnetatmo.py --

Station owner :  mcinflyre@gmail.com
Data units    : imperial

Rain Gauge
                   sum_rain_24 : 0.5
                     rf_status : 54
                          When : 18:57:36
                          Rain : 0
                    battery_vp : 5792
                    sum_rain_1 : 0.486163993585
Study
                           CO2 : 648
                     rf_status : 80
                   Temperature : 20.2
                          When : 18:56:51
                    temp_trend : up
                      Humidity : 61
                 date_min_temp : 1547812960
                      min_temp : 18.3
                 date_max_temp : 1547859411
                    battery_vp : 5829
                      max_temp : 20.2
Main Station
                           CO2 : 597
                   Temperature : 21.2
                          When : 18:57:39
                    temp_trend : stable
                      Humidity : 60
                      Pressure : 1007.5
                         Noise : 46
                      min_temp : 19.7
              AbsolutePressure : 1003.1
                pressure_trend : down
                 date_max_temp : 1547791316
                 date_min_temp : 1547812705
                   wifi_status : 12
                      max_temp : 21.6
Outdoors
                 date_min_temp : 1547796105
                     rf_status : 71
                   Temperature : 19.4
                          When : 18:57:23
                    temp_trend : stable
                      Humidity : 100
                      min_temp : 10.2
                 date_max_temp : 1547848317
                    battery_vp : 5774
                      max_temp : 19.8
Wind Gauge
                     rf_status : 64
             date_max_wind_str : 1547843498
                  GustStrength : 5
                          When : 18:57:36
                  WindStrength : 3
                     GustAngle : 159
                  max_wind_str : 11
                max_wind_angle : 148
                    battery_vp : 5526
                     WindAngle : 135
Alexas Room
                           CO2 : 565
                     rf_status : 84
                   Temperature : 21.2
                          When : 18:57:17
                    temp_trend : stable
                      Humidity : 58
                 date_min_temp : 1547812371
                      min_temp : 19.6
                 date_max_temp : 1547791298
                    battery_vp : 5386
                      max_temp : 21.3

**Comment by philippelt** [comment]
In fact, the unit property is just a way for the Netatmo web interface to remember user preferences.

All services always return the same units (temperature in celsius, wind in meter per second, ...). The unit setting are used to convert this data for display if the user as other preferences.

As this is the situation in place since day 1, I assumed that every one using the API already performed conversion when needed. The ability to access unit setup will just allow to build programs that are able to adapt dynamically to user preferences.

Therefore, if there are enough developers that think that is may be useful to do the math automatically, why not add it to the library (in an optional way to avoid change on the current behavior).

Open for vote...   😃

**Comment by mcinflyre** [comment]
My intention was not to ask you to do a lot of work to change the great code you already have in place.  The way I read the Netatmo API information, I was under the impression that there was a way to request the data in either metric or imperial values based on the request string.  Since that does not appear to be the case, I am fine doing the conversions on my end.

While it would be nice to have the option to select metric or imperial data from your code, no one else has requested this and I'm sure you have better things to do.

So my vote is leave the code as is since I'm the only one who requested this and it's not a simple change to the way the data is requested from Netatmo.

Thanks.

**Comment by philippelt** [comment]
Your question was good.

In fact, I am a "metric" guy so I never had problem with Netatmo unit choices but I understand your point because I would not like to get temperature returned in Farenheit when I look at it.

If it has been the case, I would have already implemented conversion in my consuming programs and would probably not need anything from the library.

But just in case some would find this useful, I will let the topic open to gather potential feedback.

Thanks for your contribution

**Comment by philippelt** [comment]
Well, it seems that nobody looks interested by a change, closing the issue

**Comment by mcinflyre** [comment]
Thanks Phillippe, I will update my code to handle the conversions on my end.
