### ISSUE TITLE
How to know if the boiler is working? (thermostat)

### ISSUE THREAD

**Issue by DLAcoding** [philippelt/netatmo-api-python#34]
Hi,

I am trying to measure of how much time the boiler is working each month. The thing is that I cannot find in the thermostat response ( `thermostat.getThermostat()`) any data that says is working. I compared tow different responses, one while the boiler was working and other while not. The only difference I found was in the timestamp datas...

Do you know if I am missing something?

Thanks for your help

**Comment by philippelt** [comment]
Hello,

sorry but I do not own a thermostat and, as a consequence, I can't develop any code for it.

An other user kindly gave me an access to his thermostat for some time that allows me to develop some start code but, as Netatmo already made changes in their API, I am not sure of what is available but not covered and what is still working.

And, by the way, I currently have limited spare time available to work on the constantly changing Netatmo API.

Regards
Philippe
