### ISSUE TITLE
Using samples/weather2file to download old data returns Device not found

### ISSUE THREAD

**Issue by aolik08** [philippelt/netatmo-api-python#55]
trying to use weather2file to try to download old data seems it is not working. even if the {module_name} is properly identified it seems it returns  ERROR: code=404, reason=Not Found, body=b'{"error":{"code":9,"message":"Device not found"}}'

```
PYTHONPATH=. ./samples/weather2file --format csv
 INFO: Previous file ./weatherdata.csv not found. Setting empty DataFrame
 INFO: Timezone Europe/Bucharest extracted from data.
 INFO: Processing MasterBedroom...
 INFO: Collecting data for MasterBedroom...
 ERROR: code=404, reason=Not Found, body=b'{"error":{"code":9,"message":"Device not found"}}'
 WARNING: None received. Aborting data collection from module MasterBedroom
 INFO: Collected data from MasterBedroom contains 0 samples.
Traceback (most recent call last):
  File "./samples/weather2file", line 642, in <module>
    main()
  File "./samples/weather2file", line 613, in main
    df_handler.append(
  File "./samples/weather2file", line 150, in append
    self.df = self.df.append(df).reset_index(drop=True)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

it seems that the issue is from here, but i am not an expert on python

```
            # Get new data from Netatmo
            d = self._get_field_dict(station_mac,
                               module_data_overview['_id'],
                               module_data_overview['data_type'],
                               module_start_date_timestamp,
                               end_date_timestamp)
            
            retreived_module_data = self._get_measurement(d) 
```

is there something that i do wrong?

**Comment by aolik08** [comment]
The weather2file was not changed in 3 years and, from what I remember, some big changes were performed on Netatmo API side.
From what I can understand it seems that on line [471             d = self._get_field_dict(station_mac,](https://github.com/philippelt/netatmo-api-python/blob/8e2d606b419b765fa66b24af700488fdffdf14ac/samples/weather2file#L471)
"station_mac" is having the value devices.station_name from Netatmo API, instead of devices._id

in my case, i don't know why this field is composed from the following fields: "home_name" + " " + "(" + device.module_name + ")" it has a space char between home_name and device.module_name
![image](https://github.com/philippelt/netatmo-api-python/assets/117927029/9c3da630-a419-4f3d-a58b-d39ed7bac8e3)

If i just hard-code the station_mac of my weather station, just before, i get some values, but the weather2filescript is havin issues interpreting it:
![image](https://github.com/philippelt/netatmo-api-python/assets/117927029/757ed9de-f075-4ba9-93a8-0e9b2b84cd21)

"something fishy is going on..."

**Comment by philippelt** [comment]
Unfortunately, this sample code was developped by @joebe975 and being just a sample code I did not invest time on it to update it with netatmo evolution.

May be I will have to remove it if @joebe975 can no longer maintain it...

**Comment by aolik08** [comment]
ah, ok... thank you for that
