### ISSUE TITLE
Authentication request rejected

### ISSUE THREAD

**Issue by bergerbyte** [philippelt/netatmo-api-python#59]
Hello,

Firstly, thank you for your assistance.

I've been facing challenges with the authentication process. Every time I attempt to authenticate, I receive the error "Authentication request rejected." I've set up my configuration using the .netatmo.credentials method.

I've created the Refresh-Token through Netatmo, but on a reload, it's no longer visible. Oddly, when I recreate it, I get the same token value. Is this the intended behavior?

Below is the error I encounter:

<img width="1053" alt="Bildschirmfoto 2023-07-21 um 17 24 19" src="https://github.com/philippelt/netatmo-api-python/assets/22369762/31065fb2-18b4-4b17-9163-154a9ee1cb1f">

Your guidance would be much appreciated.

**Comment by rvk01** [comment]
Can you try this in a python script, just to rule out permission errors on your cred. file.

```
import lnetatmo

CLIENT_ID = '1234'
CLIENT_SECRET = '123abc'
REFRESH_TOKEN = 'xyz|abc'

authorization = lnetatmo.ClientAuth(
        clientId=CLIENT_ID,
        clientSecret=CLIENT_SECRET,
        refreshToken=REFRESH_TOKEN,
        )
```

**Comment by bergerbyte** [comment]
Ok, problem found. The package was still on version 2.1. Thanks for the help.
