### ISSUE TITLE
KeyError: 'home_name'

### ISSUE THREAD

**Issue by JurgenLB** [philippelt/netatmo-api-python#63]
I was testing your python script with my Thermostat and got a 
`KeyError: 'home_name'`
on line 308
`self.thermostatData['name'] = self.thermostatData['home_name']`
and line 311
`self.defaultThermostat = self.thermostatData['home_name']`

I changed it to `['station_name']` and now it give no Error's more.
This is the name for the Relaisstation,
Was this the intended "name" or do you mean the name of the thermostat ?

I see another reference on line 350 but I think there it is OK

**Comment by philippelt** [comment]
I am currently overloaded, I will try to find some free time in the coming weeks.

Sorry for the delay

**Comment by JurgenLB** [comment]
That's OK
Take Your Time, I notice that `getthermostatsdata` is from the OLD API 
So that's a bigger change than I first thought 

Kind regards

**Comment by JurgenLB** [comment]
this is resolved in #71
