### ISSUE TITLE
Python Package Index

### ISSUE THREAD

**Issue by fabaff** [philippelt/netatmo-api-python#7]
It would be nice if you publish releases at PyPI.

`netatmo-api-python` is a dependency of [Home Assistant](https://home-assistant.io) and since there are no archives of releases available it makes it hard to track changes. 

Thanks.

**Comment by HydrelioxGitHub** [comment]
I will publish it to the PyPI as soon as possible. (I'm the owner of the package)

**Comment by HydrelioxGitHub** [comment]
It could be better if the structure of the Github project respect these guidelines : [Publish to Pypi](http://peterdowns.com/posts/first-time-with-pypi.html)

Add a tag or a release, add a setup.cfg
Could you do that or accept a PR ?

**Comment by philippelt** [comment]
You are absolutely right, added that to my todo list...
:-)

**Comment by jschlyter** [comment]
Need help? I can create a PR and @HydrelioxGitHub has offered help as well.

**Comment by philippelt** [comment]
Hello, I am not dead, just overloaded, but I do not forget my todo list !
Back to Netatmo soon...

**Comment by philippelt** [comment]
@HydrelioxGitHub, up to you to upload the new version if you have all required parts...
Have a good day

**Comment by HydrelioxGitHub** [comment]
The upload on Pypi is done. I've not done any test yet, just push the github repo.
[Link here](https://pypi.python.org/pypi/lnetatmo)

It could be good to add or rename the readme file because Pypi does not accept .md format. For the next time ! 
Thanks for your work !

**Comment by philippelt** [comment]
Thanks
