### ISSUE TITLE
Sample printThermostat.py not working

### ISSUE THREAD

**Issue by xMadNet** [philippelt/netatmo-api-python#70]
Hi,
Got 
"Traceback (most recent call last):
  File "/mnt/RasPi/Dev/Netatmo/netatmo-api-python/samples/printThermostat.py", line 13, in <module>
    thermostat = lnetatmo.ThermostatData(authorization)
  File "/usr/local/lib/python3.9/dist-packages/lnetatmo.py", line 309, in __init__
    self.thermostatData['name'] = self.thermostatData['home_name']
KeyError: 'home_name'"
In resp = postRequest("Thermostat", _GETTHERMOSTATDATA_REQ, postParams) there is no entry named 'home_name'
Regards

**Comment by JurgenLB** [comment]
this issue is already on the list see #63

**Comment by JurgenLB** [comment]
This is resolved I #71
