### ISSUE TITLE
modulesNamesList() function parameter 

### ISSUE THREAD

**Issue by Straumleaf** [philippelt/netatmo-api-python#77]
Hi!
First of all I would like to thank you for your library. Very useful one and easy to use.
And I found one anomaly maybe, in above mentioned function. When I pass 'None' I am getting an exception but if I pass ' ' (space) just one symbol or any string like 'sdhfkjshkjfh' I am getting all sensors data as if I passed the name of my station.

**Comment by philippelt** [comment]
Thanks for reporting. It should have been fixed by https://github.com/philippelt/netatmo-api-python/commit/e6c7c0d439fdae6fc670e318d57fdf67f8997747
