### ISSUE TITLE
Netatmo API changes on November 30th.

### ISSUE THREAD

**Issue by ot3** [philippelt/netatmo-api-python#8]
Today I received the following mail from Netatmo:

> Switch to Getthermostatsdata, Gethomedata and Getstationsdata by November 30th.
> 
> Friendly reminder: Getthermstate, Getuser and Devicelist will move from deprecated to shut down. On November 30th, we are proceeding to a structural change to make our APIs faster and more powerful. Unfortunately, old and deprecated API methods won’t be supported anymore. Make sure you amend your code and start using newer methods as soon as possible for a smooth transition:
> 
> Replace Getthermstate with Getthermostatdata
> Replace Getuser with Getthermostatdata, Gethomedata or Getstationsdata
> Replace Devicelist with Getthermostatdata or Getstationsdata
> 

Question: is this module compatible with the changes in the Netatmo API?

**Comment by philippelt** [comment]
Yes, the library has been updated to the new Netatmo APIs.

A compatibility class has been setup so you just need the last library version and do not have to change your application if you don't want to. Only a deprecation warning will be issued.

I have on my to do list to change the repo setup for Pypi update (the current available pipit release is outdated). In the meantime, download lnetatmo.py directly from Github (it's a single module library, easy to include manually in your project).
