### ISSUE TITLE
Weather2file.py does not seem to download all weather data. 

### ISSUE THREAD

**Issue by markdebont** [philippelt/netatmo-api-python#80]
Hi,

Trying to download the weather data of all my 3 units (Indoor 1, Indoor 2 and Outdoor). But it apparently does not download the data of sensor "Indoor 2" which has some data. 

See debug data below, is there anything I am doing wrong here? The created token has all the credentials. 

cheers,
Mark 

DEBUG: 1024 samples found for Outdoor. 2017-09-18 22:06:49+02:00 - 2017-09-22 11:46:45+02:00
 INFO: Hour limit hit (450 per hour). Waiting for 3474.7 seconds...
 WARNING: Your current token scope do not allow access to Weather station
 WARNING: None received. Aborting data collection from module Outdoor
 INFO: Collected data from Outdoor contains 359424 samples.
 INFO: Processing Indoor 2...
 INFO: Collecting data for Indoor 2...
 WARNING: Your current token scope do not allow access to Weather station
 WARNING: None received. Aborting data collection from module Indoor 2
 INFO: Collected data from Indoor 2 contains 0 samples.
 DEBUG: Saving to file .\netatmo_1.csv (1379174 samples)
 DEBUG: .\netatmo_1.csv saved`

**Comment by philippelt** [comment]
Hello Mark, sorry for the delay.

It seems that the token you created using the Netatmo web site do not have an appropriate scope for your requests.

There is something that looks like maybe a bug in the netatmo scope definition (see https://github.com/philippelt/netatmo-api-python/issues/56#issuecomment-1638546613)
