### ISSUE TITLE
imghdr missing

### ISSUE THREAD

**Issue by DetlefR** [philippelt/netatmo-api-python#87]
This is only for information.
I'm running lnetatmo.py in a docker environment. After the last update, an error occur 
"No module named 'imghdr'". 

It seems, that 'imghdr' is removed in the newest python version.
For me, a downgrade to python 3.12 was the solution. 
Maybe this issue should be respected in a newer version.

Best regards
Detlef

Btw: Thanks for this API. They are working very well.

**Comment by philippelt** [comment]
Thanks for the info.
As the camera consistently returned jpeg content for camera pictures, this library can be removed without too much risk.
I want to avoid adding a non standard library dependency and they are the only replacement for imghdr (filetype, Pillow, ...)
Applications using getCameraPicture should check image content with Pillow before use.

**Comment by rvk01** [comment]
Imghdr.py isn't that large. Some code for image detection could easily be added. Otherwise you could download and add the imghdr.py yourself. No need to downgrade python for that.

https://github.com/python/cpython/blob/3.11/Lib/imghdr.py
