### ISSUE TITLE
Homecoach Fixme ?

### ISSUE THREAD

**Issue by JurgenLB** [philippelt/netatmo-api-python#88]
So this is the data from my 3 Homecoach devices.
It is a list of dictionary's and nested list/dictionary's.

`[{'_id': 'xxxxxxxx', 'station_name': 'Lars', 'date_setup': 1529693878, 'last_setup': 1529693878, 'type': 'NHC', 'last_status_store': 1730457334, 'firmware': 59, 'last_upgrade': 1529693879, 'wifi_status': 78, 'reachable': True, 'co2_calibrating': False, 'data_type': ['Temperature', 'CO2', 'Humidity', 'Noise', 'Pressure', 'health_idx'], 'place': {'altitude': xx, 'city': 'xxxx', 'country': 'xx', 'timezone': 'Europe/Brussels', 'location': [xxxx,xxxx]}, 'dashboard_data': {'time_utc': 1730457334, 'Temperature': 18.5, 'CO2': 604, 'Humidity': 63, 'Noise': 36, 'Pressure': 1027.4, 'AbsolutePressure': 1019.6, 'health_idx': 0, 'min_temp': 18.4, 'max_temp': 19.2, 'date_max_temp': 1730416110, 'date_min_temp': 1730447030}}, {'_id': 'xxxxxxxx', 'station_name': 'meisjes', 'date_setup': 1529695076, 'last_setup': 1529695076, 'type': 'NHC', 'last_status_store': 1730457115, 'firmware': 59, 'last_upgrade': 1529695077, 'wifi_status': 77, 'reachable': True, 'co2_calibrating': False, 'data_type': ['Temperature', 'CO2', 'Humidity', 'Noise', 'Pressure', 'health_idx'], 'place': {'altitude': xx, 'city': 'xxxx', 'country': 'xx', 'timezone': 'Europe/Brussels', 'location': [xxxx,xxxx]}, 'dashboard_data': {'time_utc': 1730457113, 'Temperature': 18.6, 'CO2': 656, 'Humidity': 62, 'Noise': 36, 'Pressure': 1028.6, 'AbsolutePressure': 1020.7, 'health_idx': 0, 'min_temp': 18.6, 'max_temp': 19.3, 'date_max_temp': 1730415889, 'date_min_temp': 1730449231}}, {'_id': 'xxxxxxxx', 'station_name': 'Slaapkamer', 'date_setup': 1529696933, 'last_setup': 1529696933, 'type': 'NHC', 'last_status_store': 1730457129, 'firmware': 59, 'last_upgrade': 1529696984, 'wifi_status': 60, 'reachable': True, 'co2_calibrating': False, 'data_type': ['Temperature', 'CO2', 'Humidity', 'Noise', 'Pressure', 'health_idx'], 'place': {'altitude': xx, 'city': 'xxxxxx', 'country': 'xx', 'timezone': 'Europe/Brussels', 'location': [xxxx,xxxx]}, 'dashboard_data': {'time_utc': 1730457129, 'Temperature': 19.5, 'CO2': 620, 'Humidity': 60, 'Noise': 36, 'Pressure': 1026.7, 'AbsolutePressure': 1018.9, 'health_idx': 0, 'min_temp': 19.4, 'max_temp': 20.1, 'date_max_temp': 1730445039, 'date_min_temp': 1730448062}}]
`

Do you think this is better;

`def HomecoachDevice(self, id=""):
    for device in self.rawData:
        if id in device['_id']:
            return device

`

**Comment by philippelt** [comment]
If I assume that the response is always a list of device and that each device has an '_id' property, I think that what you meant is rather :  
```python
def HomecoachDevice(self, id=""):
    for device in self.rawData:
        if device['_id'] == id:
            return device
    return None
```

This return the full device instance for which the `device['_id']` has the value supplied as the id parameter and None if no device with this id exists.

Is that the expected behavior ?
