### ISSUE TITLE
Error code=400, reason=, body=b'{"error":"invalid_client"}'

### ISSUE THREAD

**Issue by Mattjcuk** [philippelt/netatmo-api-python#92]
Hi,

I'm getting the error message:

code=400, reason=, body=b'{"error":"invalid_client"}'
Traceback (most recent call last):
  File "/home/mc/Programming/Python/netatmo.py", line 5, in <module>
    weatherData = lnetatmo.WeatherStationData(authorization)
  File "/usr/local/lib/python3.11/dist-packages/lnetatmo.py", line 416, in __init__
    self.getAuthToken = authData.accessToken
  File "/usr/local/lib/python3.11/dist-packages/lnetatmo.py", line 241, in accessToken
    if self.expiration < time.time() : self.renew_token()
  File "/usr/local/lib/python3.11/dist-packages/lnetatmo.py", line 252, in renew_token
    if self.refreshToken != resp['refresh_token']:
TypeError: 'NoneType' object is not subscriptable
>>> 

when running the line: 

weatherData = lnetatmo.WeatherStationData(authorization)

But the line:

The line authorization = lnetatmo.ClientAuth("netatmo.credentials") runs fine (this is before the line that causes the error)

I did notice this error came in an another issue but it seemed to resolved itself, I'm still getting it though.

Kind regards,

Matthew

**Comment by philippelt** [comment]
In your title, you mention an error 'invalid_client'. I don't see that in your comment.  

If your authentication is fine, then the above error means that a weather station (selected by default as you don't provide the station parameter) was not found in your account.

**Comment by JurgenLB** [comment]
I think your authentication line must be
`authorization = lnetatmo.ClientAuth()`
This works for me, if the ".netatmo.credentials" is in the correct place.
Don't forget the dot in front

**Comment by Mattjcuk** [comment]
Thank you, so its this line:

weatherData = lnetatmo.WeatherStationData(authorization)

that is causing the error, where do I provide the station name please?  My outdoor module is called "Outdoor Module"

Many thanks,

Matthew

**Comment by JurgenLB** [comment]
I do use
`WeatherStation = lnetatmo.WeatherStationData(authorization)`
so I think your authorization code or token/scope are not correct.

**Comment by Mattjcuk** [comment]
> I think your authentication line must be
> `authorization = lnetatmo.ClientAuth()`
> This works for me, if the ".netatmo.credentials" is in the correct place.
> Don't forget the dot in front

Thank you, I get the same error message with the .netatmo.credentials, the authorisation seems to be working fine.

Kind regards,

Matthew

**Comment by Mattjcuk** [comment]
> I do use
> `WeatherStation = lnetatmo.WeatherStationData(authorization)`
> so I think your authorization code or token/scope are not correct.

Thank you, I will investigate further.

Kind regards,

Matthew

**Comment by philippelt** [comment]
Netatmo servers are currently failing multiple times per day with errors code varying from 500 error to invalid scope.

Be sure to retry your code 3 or 4 times without change at different moments to ensure that it is not a transient condition.
