### ISSUE TITLE
Error : invalid_grand

### ISSUE THREAD

**Issue by TheudRikMo** [philippelt/netatmo-api-python#93]
Bonjour,
J'ai installé votre API sous MacOS Sequioa, initialisé le fichier ".netatmo.credentials" avec les données que j'ai récupérés via "Netatmo connect" de mon compte d'appli. avec le scope "read_station".
J'ai essayé le code de votre exemple "SimpleLastData.py" et j'obtiens les erreurs :

code=400, reason=, body=b'{"error":"invalid_grant"}'
Traceback (most recent call last):
  File "/Users/TMo/Documents/Dev/Python/netatmo/test1.py", line 13, in <module>
    devList = lnetatmo.WeatherStationData(authorization)
  File "/Users/TMo/Documents/Dev/Python/netatmo/lnetatmo.py", line 418, in __init__
    self.getAuthToken = authData.accessToken
  File "/Users/TMo/Documents/Dev/Python/netatmo/lnetatmo.py", line 240, in accessToken
    if self.expiration < time.time() : self.renew_token()
  File "/Users/TMo/Documents/Dev/Python/netatmo/lnetatmo.py", line 251, in renew_token
    if self.refreshToken != resp['refresh_token']:
TypeError: 'NoneType' object is not subscriptable

Quelle donnée ou manip ai-je omis ?

Par avance merci de votre aide.

**Comment by JurgenLB** [comment]
duplicate of #92 
Please check your token / Veuillez vérifier votre token

**Comment by philippelt** [comment]
Netatmo servers are currently failing multiple times per day.

Be sure to retry your code 3 or 4 times at different moments to ensure that it is not a transient condition.

**Comment by TheudRikMo** [comment]
Bonjour,
Merci pour vos retours.
J'ai, bien évidemment, essayé plusieurs fois sur plusieurs jours.
Je viens de faire un nouveau test, paprès avoir demandé un nouveau token, avec la même réponse infructueuse.
Je voudrais juste être sûr de ne pas faire d'erreur d'interprétation des données fournies et à fournir à votre API...
Sur la page de mon appli Netatmo connect, lorsque je demande un token "read_station" j'obtiens un "Access Token" de la forme : xxxxxxxxxxxxxxxxxxxxxxxx|yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy, et un "Refresh token" de la forme : kkkkkkkkkkkkkkkkkkkkkkkk|vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.
Et dans le fichier ".netatmo.credentials", en plus de "CLIENT_ID" et "CLIENT_SECRET" immuables, j'indique dans "REFRESH_TOKEN" la valeur ci-avant "kkkkkkkkkkkkkkkkkkkkkkkk|vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv".
Et je lance "SimpleLastData.py" avec Python3.
Est-ce bien tout ce que je dois faire ?
Par avance merci.

**Comment by philippelt** [comment]
Depuis l'introduction du paramètre home, il est nécessaire de passer par homeData pour énumérer les stations donc le seul scope read_station ne suffit plus. Voir https://github.com/philippelt/netatmo-api-python/issues/56#issuecomment-1638546613

Sinon le reste me parait Ok
